---
apiVersion: v1
kind: Service
metadata:
  name: adapter
  namespace: email-dev
spec:
  ports:
    - name: http-8000
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: adapter
  sessionAffinity: None
  type: ClusterIP
