from enum import Enum


class Context:
    IMAP = "IMAP"
    SMTP = "SMTP"
    Sieve = "Sieve"


class Command(Enum):
    LIST_MAIL = "LIST_MAIL"
    FETCH_MAIL = "FETCH_MAIL"
    PEEK_MAIL = "PEEK_MAIL"
    DELETE_MAIL = "DELETE_MAIL"
    COPY_MAIL = "COPY_MAIL"
    SEND_MAIL = "SEND_MAIL"
    APPEND_MAIL = "APPEND_MAIL"
    CREATE_MAILBOX = "CREATE_MAILBOX"
    RENAME_MAILBOX = "RENAME_MAILBOX"
    DELETE_MAILBOX = "DELETE_MAILBOX"
    LIST_MAILBOX = "LIST_MAILBOX"
    DOWNLOAD_ATTACHMENT = "DOWNLOAD_ATTACHMENT"
    ADD_FLAGS = "ADD_FLAGS"
    REMOVE_FLAGS = "REMOVE_FLAGS"
    PUT_AUTOREPLY_SCRIPT = "PUT_AUTOREPLY_SCRIPT"
    GET_AUTOREPLY_SCRIPT = "GET_AUTOREPLY_SCRIPT"
    ACTIVATE_AUTOREPLY_SCRIPT = "ACTIVATE_AUTOREPLY_SCRIPT"
    DEACTIVATE_AUTOREPLY_SCRIPT = "DEACTIVATE_AUTOREPLY_SCRIPT"
    PUT_SCRIPT = "PUT_SCRIPT"
